basePath: /api
definitions:
  auth.LoginRequest:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  auth.ResetPasswordRequest:
    properties:
      confirmPassword:
        maxLength: 20
        minLength: 6
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
    required:
    - confirmPassword
    - password
    type: object
  auth.SendEmailForgotPasswordRequest:
    properties:
      email:
        maxLength: 30
        type: string
    required:
    - email
    type: object
  auth.SendEmailRegisterRequest:
    properties:
      email:
        maxLength: 30
        type: string
      fullname:
        maxLength: 30
        type: string
      password:
        maxLength: 20
        minLength: 6
        type: string
      username:
        maxLength: 15
        type: string
    required:
    - email
    - fullname
    - password
    - username
    type: object
  auth.Tokens:
    properties:
      accessToken:
        type: string
      refreshToken:
        type: string
    type: object
  auth.VerifyOTPRequest:
    properties:
      otp:
        type: string
    required:
    - otp
    type: object
  response.SwaggerBadRequestResponse:
    properties:
      errorFields:
        additionalProperties:
          type: string
        type: object
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
  response.SwaggerResponse:
    properties:
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
  response.SwaggerResponseWithData:
    properties:
      data: {}
      message:
        type: string
      status:
        type: integer
      success:
        type: boolean
    type: object
  user.ProviderType:
    enum:
    - LOCAL
    - GOOGLE
    - GITHUB
    type: string
    x-enum-varnames:
    - ProviderTypeLocal
    - ProviderTypeGoogle
    - ProviderTypeGithub
  user.Role:
    enum:
    - USER
    - ADMIN
    type: string
    x-enum-varnames:
    - RoleUser
    - RoleAdmin
  user.SecureUser:
    properties:
      createdAt:
        type: string
      dateOfBirth:
        type: string
      email:
        type: string
      fullname:
        type: string
      id:
        type: string
      info:
        type: string
      profileBackgroundUrl:
        type: string
      profileUrl:
        type: string
      providerType:
        $ref: '#/definitions/user.ProviderType'
      role:
        $ref: '#/definitions/user.Role'
      updatedAt:
        type: string
      username:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:5000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is api for social media application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Social Media API
  version: "1.0"
paths:
  /auth/forgot-password/resend-email:
    post:
      description: authentication and resend email forgot password
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/forgot-password/reset-password:
    patch:
      consumes:
      - application/json
      description: authentication and reset password
      parameters:
      - description: reset password payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.ResetPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.SwaggerBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/forgot-password/send-email:
    post:
      consumes:
      - application/json
      description: send email to verify otp and set cookie
      parameters:
      - description: send email forgot password payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.SendEmailForgotPasswordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.SwaggerBadRequestResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/forgot-password/verify-otp:
    post:
      consumes:
      - application/json
      description: authentication verify otp and set cookie
      parameters:
      - description: verify otp forgot password payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.SwaggerBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/github:
    get:
      description: redirect to github login
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      summary: login with github
      tags:
      - auth
  /auth/github/callback:
    get:
      description: authentications set cookies and redirect
      responses:
        "308":
          description: Permanent Redirect
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      summary: github login callback
      tags:
      - auth
  /auth/google:
    get:
      description: redirect to google login
      responses:
        "307":
          description: Temporary Redirect
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      summary: login with google
      tags:
      - auth
  /auth/google/callback:
    get:
      description: authentications set cookies and redirect
      responses:
        "308":
          description: Permanent Redirect
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      summary: google login callback
      tags:
      - auth
  /auth/login:
    post:
      consumes:
      - application/json
      description: authentication and set cookie
      parameters:
      - description: login payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.SwaggerBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/logout:
    post:
      description: authentication and clear cookies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/profile:
    get:
      description: authentication and set cookie
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SwaggerResponseWithData'
            - properties:
                data:
                  $ref: '#/definitions/user.SecureUser'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/refresh-token:
    post:
      description: authentication refresh token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.SwaggerResponseWithData'
            - properties:
                data:
                  $ref: '#/definitions/auth.Tokens'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/register/resend-email:
    post:
      description: authentication and resend email register
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/register/send-email:
    post:
      consumes:
      - application/json
      description: create user store send email to verify otp and set cookie
      parameters:
      - description: send email register payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.SendEmailRegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.SwaggerBadRequestResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
  /auth/register/verify-otp:
    post:
      consumes:
      - application/json
      description: "authentication\tverify otp and create user"
      parameters:
      - description: verify otp register payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/auth.VerifyOTPRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.SwaggerBadRequestResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.SwaggerResponse'
      tags:
      - auth
swagger: "2.0"
